openapi: 3.1.0
info:
  version: 1.0.0
  title: Blog API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: API for the story platform (authors, users, articles)
tags:
  - name: Auth
    description: User registration, login, logout
  - name: Users
    description: Users (authors, profile, saved articles)
  - name: Stories
    description: Stories (posting, editing, filtering)
servers:
  - url: http://localhost:3000/api
    description: Local server
paths:
  /auth/register:
    post:
      $ref: '../swagger/paths/auth/register.yaml'
  # /auth/login:
    # post:
      # $ref: '../swagger/paths/auth/login.yaml'
  /auth/logout:
    post:
      $ref: '../swagger/paths/auth/logout.yaml'
  # /auth/refresh:
  #   post:
  #     $ref: '../swagger/paths/auth/refresh.yaml'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
